name: random_icons
description: "app generating random icons."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.6
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
flutter_icons:
  ios: true
  image_path: "assets/images/icon.png"

flutter_launcher_icons:
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'
